# Generated by Django 3.1.7 on 2021-04-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('mass_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectuser',
            name='from_email',
            field=models.CharField(help_text='Entery Sender Gmail', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='selectuser',
            name='message',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='selectuser',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selectuser',
            name='user',
            field=models.ManyToManyField(to='account.EmailAddress'),
        ),
    ]
