# Generated by Django 3.1.7 on 2021-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('mass_mail', '0003_auto_20210413_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectuser',
            name='user',
        ),
        migrations.AddField(
            model_name='selectuser',
            name='email',
            field=models.ManyToManyField(to='account.EmailAddress'),
        ),
    ]
