# Generated by Django 3.1.7 on 2021-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('mass_mail', '0004_auto_20210413_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='The Subject field is a brief description of the message', max_length=200, null=True)),
                ('message', models.CharField(help_text='what ever message you want to send your recipient inbox', max_length=1500, null=True)),
                ('from_email', models.CharField(help_text='Entery Sender(your) Gmail', max_length=40, null=True)),
                ('email', models.ManyToManyField(to='account.EmailAddress')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectUser',
        ),
    ]
