# Generated by Django 3.1.7 on 2021-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mail', '0005_auto_20210413_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmail',
            name='message',
            field=models.TextField(help_text='what ever message you want to send your recipient inbox', max_length=1500, null=True),
        ),
    ]
