# Generated by Django 3.1.7 on 2021-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_mail', '0006_auto_20210413_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='attach_a_file',
            field=models.FileField(blank=True, null=True, upload_to='mail_attach_file'),
        ),
        migrations.AlterField(
            model_name='sendmail',
            name='message',
            field=models.TextField(help_text='What ever message you want to send your recipient inbox', max_length=1500, null=True),
        ),
    ]
